package mx.ipn.model;
// Generated 28/05/2017 03:52:46 PM by Hibernate Tools 4.3.1



/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idEmpleado;
     private String nombreEmpleado;
     private String paternoEmpleado;
     private String maternoEmpleado;
     private String email;

    public Empleado() {
    }

    public Empleado(String nombreEmpleado, String paternoEmpleado, String maternoEmpleado, String email) {
       this.nombreEmpleado = nombreEmpleado;
       this.paternoEmpleado = paternoEmpleado;
       this.maternoEmpleado = maternoEmpleado;
       this.email = email;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getNombreEmpleado() {
        return this.nombreEmpleado;
    }
    
    public void setNombreEmpleado(String nombreEmpleado) {
        this.nombreEmpleado = nombreEmpleado;
    }
    public String getPaternoEmpleado() {
        return this.paternoEmpleado;
    }
    
    public void setPaternoEmpleado(String paternoEmpleado) {
        this.paternoEmpleado = paternoEmpleado;
    }
    public String getMaternoEmpleado() {
        return this.maternoEmpleado;
    }
    
    public void setMaternoEmpleado(String maternoEmpleado) {
        this.maternoEmpleado = maternoEmpleado;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


